### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by martinpihrt** [Rimco/OSPy-plugins-core#2]
Hi,
**Thank you very much for modifying the weather on stormglas, I have incorporated your changes into my version of OSPy. I also modified the "rain delay" extension.**

The "weather_based_water_level" extension reports an error

Traceback (most recent call last):
   File "/OSPy/plugins/weather_based_water_level/__init__.py", line 85, in run
     total_info['rain_mm'] += weather.get_rain(check_date)
   File "/OSPy/ospy/weather.py", line 42, in func_wrapper
     for key in self._result_cache[cache_name].keys():
RuntimeError: dictionary changed size during iteration

Is the extension working for you? Is there still a bug in weather.py?

Thanks
Martin

**Comment by Rimco** [comment]
I think your version is having a slightly different implementation, please check "def _cache(cache_name)" in weather.py and make sure it's the same:

This is my version:
            for key in list(self._result_cache[cache_name].keys()):
                if (datetime.date.today() - key).days > 30:
                    del self._result_cache[cache_name][key]

The rain delay plug-in was also updated and should work. See [a5ff432](https://github.com/Rimco/OSPy-plugins-core/commit/a5ff4321c72128d0fe1551edb1ebfc5a8feb98cd).

**Comment by martinpihrt** [comment]
Thank you very much,
yes I had a mistake there.

for key in self._result_cache[cache_name].keys():
for key in **list**(self._result_cache[cache_name].keys()):

I confirm that the delay and level are now working as they should. Hopefully the stormaglass service will work for some time like dark sky was before apple bought it.
Thank you very much and I appreciate it.

I still want to ask about the plugin update.
It says these messages that it should be adjusted. can i ignore it?

hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.

Martin

**Comment by Rimco** [comment]
Good it works now.

Sounds like your local Git is not having a default configuration, but will not break anything in this case (because you won't have this situation). If you want you could just go to that directory and run "git config pull.rebase false", it should stop that message.

**Comment by martinpihrt** [comment]
Yes it helped, thanks for the explanation and help
Martin
